name: Auto PR from main to develop

on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Print github
        run: echo '${{ toJson(github) }}'

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Create and merge pull request
        run: |
          gh pr create -B develop -H main --title 'Merge main into develop' --body 'Merge main into develop'
          gh pr merge main --merge --auto --body 'Merge main into develop'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  