name: Update version

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Run release-please
        id: release_please
        uses: GoogleCloudPlatform/release-please-action@v3
        with:
          token: ${{ secrets.RELEASE_PR_TOKEN }}         
          release-type: node
          package-name: obsidian-telegram-sync    
          include-v-in-tag: false      
                    
      - name: Extract version
        if: ${{ steps.release_please.outputs.pr_created }}
        id: extract_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update manifest.json and versions.json
        if: ${{ steps.release_please.outputs.pr_created }}
        run: node version-bump.mjs

      - name: Commit changes
        if: ${{ steps.release_please.outputs.pr_created }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md manifest.json versions.json package.json
          git commit -m "chore: update CHANGELOG.md, manifest.json, versions.json and package.json to version $VERSION"

      - name: Push changes
        if: ${{ steps.release_please.outputs.pr_created }}
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.release_please.outputs.branch }}