name: Update version

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

      - name: Run release-please
        id: release
        uses: GoogleCloudPlatform/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node          
          package-name: obsidian-telegram-sync          
          include-v-in-tag: false     
          pull-request-title-pattern: release ${version}   
          skip-labeling: true  
    
      - name: Checkout repository
        if: ${{ steps.release.outputs.pr }}
        uses: actions/checkout@v3              

      - name: Set up Node.js
        if: ${{ steps.release.outputs.pr }}
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"      

      - name: Update manifest.json and versions.json
        if: ${{ steps.release.outputs.pr }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git fetch origin
          git checkout release-please--branches--main--components--obsidian-telegram-sync          
          npm ci          
          npm run version
          VERSION=$(node -p "require('./package.json').version")
          git commit -m "release $VERSION" 
          git push